#include <stdio.h> 
#include "HelloJNI.h"	// generated by javah

JNIEXPORT void JNICALL Java_HelloJNI_sayHi 
(JNIEnv *env, jobject obj, jstring who, jint times) { 
	jint i; 
	jboolean iscopy; 
	const char *name; 
	name = (*env)->GetStringUTFChars(env, who, &iscopy); 
	for (i = 0; i < times; i++) {
		printf("Hello %s\n", name);
	}
}
